### ISSUE TITLE
Could not get Requires Right annotation working

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/security.rightsservice-splash#1]
Set an @RequiresRight(name='[right_name]') annotation in the head of a class, or simply for a splash route.

Although my user has the right store in session ($rightService even returns true for <code>isAllowed($rightName)</code>, the annotation is failing, leading me to a 403 page...

**Comment by moufmouf** [comment]
Fixed by https://github.com/thecodingmachine/mvc.splash-common/commit/62fda6d8c153286887d57569da28eb3d6f9c073a
