### ISSUE TITLE
Add a OR condition annotation for multiple RequireRight (and maybe a AND condition annotation as well)

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/security.rightsservice-splash#2]
Is it possible to add a OR condition annotation to manage multiple RequireRight ?

I think, that for the moment, we can only made AND condition by doing:
@RequiresRight("SHOW CLASSEURS")
@RequiresRight("EDIT CLASSEUR")

If not, can you also add a AND condition annotation to manage multiple RequireRight ?

Thanks,

**Comment by moufmouf** [comment]
Done in Splash 8 (with the @Right annotation)
