### ISSUE TITLE
Annotation @RequireRight: 403 HTTP CODE

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/security.rightsservice-splash#3]
At the moment, the annotation @RequireRight responds with a 200 HTTP code with a redirect URL if the logged user doesn't have the specified required right.

Is it possible to responds with a 403 HTTP Code (Forbidden) ?

This will be very useful for ajax requests.

Thanks.

**Comment by moufmouf** [comment]
Fixed in Splash 8
